# Servidor
server.port=8080

# Banco de Dados
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:sart_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}

#H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Credenciais Iniciais do Administrador (Seed)
app.seed.admin.email=${ADMIN_SEED_EMAIL:warius18@gmail.com}
app.seed.admin.password=${ADMIN_SEED_PASSWORD:whalysonramos}
